### ISSUE TITLE
 Error installing jekyll

### ISSUE THREAD

**Issue by MurphyL** [MurphyL/cijian.us#1]
```shell
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf 
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/yajl-ruby-1.2.1 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/yajl-ruby-1.2.1/ext/yajl/gem_make.out
```

**Comment by MurphyL** [comment]
See #2

**Comment by MurphyL** [comment]
2011-09-21
